# Generated by Django 4.2.2 on 2023-06-30 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
